# The Basic

Mengimpor NumPy dengan abreviasi np

In [1]:
import numpy as np

Membuat array baru dengan method :
    - .arange : mengembalikan nilai sampai rentang nilai tertentu
    - .reshape : merombak array/matriks sesuai dengan jumlah row (argument 1) dan column (argument 2) 

In [2]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

menghasilkan array yang berisi angka dari 0 - 14 dengan bentuk 3 x 5

In [3]:
a.shape # mengetahui bentuk array

(3, 5)

In [4]:
a.ndim # mengetahui dimensi array

2

In [5]:
a.dtype.name # mengetahui tipe data di dalam array

'int64'

In [6]:
a.itemsize # mengetahui ukuran tiap elemen dalam array (dalam bytes)

8

In [7]:
a.size # jumlah elemen dalam array, 3 x 5 = 15

15

In [8]:
type(a) # mengetahui tipe data untuk variabel a

numpy.ndarray

## Membuat array baru

In [9]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [10]:
type(b)

numpy.ndarray

---

---

# Array Creation

In [11]:
a = np.array([2, 3, 4])
a

array([2, 3, 4])

In [12]:
a.dtype

dtype('int64')

In [13]:
b = np.array([1.2, 3.5, 5.1])
b

array([1.2, 3.5, 5.1])

In [14]:
b.dtype

dtype('float64')

---

In [15]:
# a = np.array(1,2,3,4) # error

kode di atas menghasilkan error, karena fungsi np.array() memerlukan list sebagai parameter

revisi kode dengan memasukkan list sebagai parameter

In [16]:
a = np.array([1,2,3,4]) 
a

array([1, 2, 3, 4])

In [17]:
b = np.array([(1.5,2,3), (4,5,6)]) # contoh array 2 dimensi
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [18]:
c = np.array( [ [1,2], [3,4] ], dtype=complex ) # contoh array dengan elemen bilangan kompleks
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

---

membuat array dengan beberapa macam isian baku, menggunakan fungsi sebagai berikut :

    * np.zeros : membuat array dengan isian angka 0
    * np.ones : membuat array dengan isian angka 1
    * np.empty : membuat array dengan isian random tergantung keadaan memori

fungsi di atas dengan dtype baku = float64
    
dimensi array didefinisikan sebagai argumen dalam masing-masing fungsi

In [19]:
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

menghasilkan array 3 x 4 dengan elemen 0. 

In [20]:
np.ones( (2,3,4), dtype=np.int16 ) 

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

menghasilkan array 3d, 2 x 3 x 4, dengan elemen 1 integer

In [21]:
np.empty((2,3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

akan menghasilkan elemen random array size sesuai dengan argumen

---

fungsi arange(), 
membuat array rentetan angka, mirip dengan fungsi range()

In [22]:
np.arange( 10, 30, 5 ) # 10 = start, 30 = stop, 5 = step

array([10, 15, 20, 25])

In [23]:
np.arange( 0, 2, 0.3 ) # menerima tipe float sebagai argumen

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

---

fungsi linspace(), membuat array dengan parameter start, stop dan jumlah elemen yang diinginkan

In [24]:
np.linspace( 0, 2, 9 )  # 9 elemen dimulai dari 0 sampai 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [25]:
from numpy import pi # impor pi dari modul numpy

x = np.linspace( 0, 2*pi, 100 )
f = np.sin(x)
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

---

# Printing Arrays¶

In [26]:
a = np.arange(6) # 1d array
a

array([0, 1, 2, 3, 4, 5])

In [27]:
b = np.arange(12).reshape(4,3) # 2d arrray
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [28]:
c = np.arange(24).reshape(2,3,4) # 3d array 
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [29]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [30]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


----

# Basic Operations

Ooperasi dasar pada array berdampak pada setiap elemen. Array baru akan dibuat yang merupakan hasil dari operasi kedua array.

In [31]:
a = np.array( [20,30,40,50] )
a

array([20, 30, 40, 50])

In [32]:
b = np.arange(4)
b

array([0, 1, 2, 3])

In [33]:
c = a - b
c

array([20, 29, 38, 47])

In [34]:
b**2

array([0, 1, 4, 9])

In [35]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [36]:
a<35

array([ True,  True, False, False])

---

Operasi pada matriks

In [37]:
A = np.array( [[1,1], [0,1]] )

In [38]:
B = np.array( [[2,0], [3,4]] )

In [39]:
A * B # elementwise product

array([[2, 0],
       [0, 4]])

In [40]:
A @ B #matrix product / dot product

array([[5, 4],
       [3, 4]])

Beberapa operasi seperti += dan *= akan memodifikasi array tanpa membuat array baru

In [44]:
a = np.ones((2,3), dtype=int)
a

array([[1, 1, 1],
       [1, 1, 1]])

In [45]:
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [46]:
b = np.random.random((2,3))
b

array([[0.27603315, 0.39858742, 0.30863536],
       [0.46804965, 0.63805393, 0.060377  ]])

In [47]:
b += a
b

array([[3.27603315, 3.39858742, 3.30863536],
       [3.46804965, 3.63805393, 3.060377  ]])

Upcasting : kondisi dimana saat mengoperasikan dua buah array yang berbeda tipe data, hasil operasi array akan menghasilkan tipe array yang lebih general

In [49]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0,pi,3)
b.dtype.name

'float64'

In [50]:
c = a+b
c

array([1.        , 2.57079633, 4.14159265])

In [51]:
c.dtype

dtype('float64')

tipe array c di-upcasting menjadi float64, karena float lebih general daripada integer

In [53]:
d = np.exp(c*1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [57]:
e = c * d
e

array([ 0.         +0.j        , -3.39802597 +2.18184738j,
       -7.02997977-10.9485448j ])

In [59]:
e.dtype

dtype('complex128')

begitu pula array e, di-upcasting menjadi tipe kompleks

---

## agregasi elemen array

In [60]:
a = np.random.random((2,3))
a

array([[0.35402429, 0.55111674, 0.09899281],
       [0.71369087, 0.17752435, 0.60296301]])

In [61]:
a.sum() # menjumlahkan seluruh elemen array

2.4983120692317202

In [62]:
a.min() # mengembalikan nilai minimum

0.09899281345632294

In [63]:
a.max() #mengembalikan nilai maksimum

0.7136908679613284

---

## Operasi dengan parameter axis

In [64]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [65]:
b.sum(axis=0) # sum tiap kolom

array([12, 15, 18, 21])

In [66]:
b.sum(axis=1) # sum tiap baris

array([ 6, 22, 38])

In [67]:
b.cumsum(axis=1) # sum kumulatif untuk tiap baris

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

---

# Universal Functions

In [68]:
B = np.arange(3)
B

array([0, 1, 2])

In [69]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [70]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [71]:
C = np.array([2., -1., 4.])
np.add(B, C)

array([2., 0., 6.])