# The Basic

Mengimpor NumPy dengan abreviasi np

In [1]:
import numpy as np

Membuat array baru dengan method :
    - .arange : mengembalikan nilai sampai rentang nilai tertentu
    - .reshape : merombak array/matriks sesuai dengan jumlah row (argument 1) dan column (argument 2) 

In [2]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

menghasilkan array yang berisi angka dari 0 - 14 dengan bentuk 3 x 5

In [3]:
a.shape # mengetahui bentuk array

(3, 5)

In [4]:
a.ndim # mengetahui dimensi array

2

In [5]:
a.dtype.name # mengetahui tipe data di dalam array

'int64'

In [6]:
a.itemsize # mengetahui ukuran tiap elemen dalam array (dalam bytes)

8

In [7]:
a.size # jumlah elemen dalam array, 3 x 5 = 15

15

In [8]:
type(a) # mengetahui tipe data untuk variabel a

numpy.ndarray

## Membuat array baru

In [9]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [10]:
type(b)

numpy.ndarray

---

---

# Array Creation

## Pembuatan array 

In [11]:
a = np.array([2, 3, 4])
a

array([2, 3, 4])

In [12]:
a.dtype

dtype('int64')

In [13]:
b = np.array([1.2, 3.5, 5.1])
b

array([1.2, 3.5, 5.1])

In [14]:
b.dtype

dtype('float64')

---

In [15]:
a = np.array(1,2,3,4) # error

ValueError: only 2 non-keyword arguments accepted

kode di atas menghasilkan error, karena fungsi np.array() memerlukan list sebagai parameter

revisi kode dengan memasukkan list sebagai parameter

In [16]:
a = np.array([1,2,3,4]) 
a

array([1, 2, 3, 4])

In [17]:
b = np.array([(1.5,2,3), (4,5,6)]) # contoh array 2 dimensi
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [18]:
c = np.array( [ [1,2], [3,4] ], dtype=complex ) # contoh array dengan elemen bilangan kompleks
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

---

membuat array dengan beberapa macam isian baku, menggunakan fungsi sebagai berikut :

    * np.zeros : membuat array dengan isian angka 0
    * np.ones : membuat array dengan isian angka 1
    * np.empty : membuat array dengan isian random tergantung keadaan memori

fungsi di atas dengan dtype baku = float64
    
dimensi array didefinisikan sebagai argumen dalam masing-masing fungsi

In [19]:
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

menghasilkan array 3 x 4 dengan elemen 0. 

In [20]:
np.ones( (2,3,4), dtype=np.int16 ) 

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

menghasilkan array 3d, 2 x 3 x 4, dengan elemen 1 integer

In [21]:
np.empty((2,3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

akan menghasilkan elemen random dengan size sesuai dengan argumen

---